services:
  gin-app:
    build: .
    container_name: gin-app
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data  # Bind mount instead of named volume
    env_file:
      - .env
    environment:
      JWT_SECRET_KEY: "my-secret-key"
      DB_PATH: "/app/data/demo.db"
      SERVER_PORT: "8080"
      POD_NAME: "aaa"
    restart: unless-stopped